# Generated by Django 4.0.6 on 2022-08-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Minutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Raised_by', models.TextField()),
                ('Actions', models.TextField()),
                ('Actioned_by', models.TextField()),
                ('Subsequent_info', models.TextField()),
                ('Date_of_completion', models.TextField()),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Minutes.post')),
            ],
        ),
    ]
