# Generated by Django 4.0.6 on 2022-08-11 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Minutes', '0002_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Atendees',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topics',
            name='Actioned_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topics',
            name='Date_of_completion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topics',
            name='Raised_by',
            field=models.CharField(max_length=100),
        ),
    ]
