# Generated by Django 4.0.6 on 2022-08-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minutes', '0004_rename_title_topics_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='Date_of_completion',
            field=models.CharField(max_length=100),
        ),
    ]
