# Generated by Django 4.0.6 on 2022-08-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minutes', '0005_alter_topics_date_of_completion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='Topic_Title',
            new_name='Title',
        ),
    ]
